### ISSUE TITLE
Issues with running 

### ISSUE THREAD

**Issue by madhuskey** [zakandrewking/optSwap#1]
Have installed all files however when run produce consistent errors. have narrowed it down to parameters not defined in create createRobustOneWayFluxesModel within the robustKnock function. however there is no description of these parameters so I cannot understand it .

**Comment by zakandrewking** [comment]
I haven't run this code in a while, so I'm not sure what could be happening. Could you be more specific about what is happening? Are parameters not being passed into that function?

**Comment by dakai2016** [comment]
When I run optSwap with the  default parameters,there are some errors. I don't know how to deal with them. The default parameters are following: 
 opt.knockType = 2;opt.targetRxn = 'EX_for(e)';opt.swapNum = -1;opt.knockoutNum = -1;opt.interventionNum = 1;opt.knockableRxns = {};opt.notKnockableRxns = {};opt.useCobraSolver = 0;opt.maxW = 1e7; opt.biomassRxn = model.rxns(model.c~=0); opt.dhRxns = {'ACALD'; 'ALCD2x'; 'ASAD'; 'DHDPRy'; 'FADRx'; 'G6PDH2r'; 'GAPD'; 'GLUDy'; 'GND'; 'HSDy'};opt.solverParams = [];opt.allowDehydrogenaseKnockout = true.
The errors are following:
Undefined function 'lpAssign' for input arguments of
type 'double'.

Error in createRobustOneWayFluxesModel (line 241)
                Prob = lpAssign( -c, model.S,
                model.row_lb, model.row_ub, lb, ub);

Error in optSwap (line 120)
    [model, yInd, yCoupledInd, qInd, qCoupledInd,
    sInd, sCoupledInd,...

**Comment by zakandrewking** [comment]
Unfortunately, this codebase is quite brittle. It also requires the tomlab optimization suite, and our license expired in 2014, so I cannot run this code right now.

For anyone still trying to use it, I just pushed a commit with some fixes that will make it a little easier. For one things, try with the model `test_models/e_coli_core.mat`, and use the updated default `dhRxns`.

**Comment by dakai2016** [comment]
When I run the optswap,there is a error showed 'Out of memory. Type HELP MEMORY for your options'. My OS is 32 bit with 4G memory.Can you help me? Thank you!
